### ISSUE TITLE
Android bugs

### ISSUE THREAD

**Issue by esper** [TheJosh/chaotic-rage#112]
Since the android app is added to Google Play it could be good to keep track of the Android bugs.

- [ ] #110. Controls not good enough.
- [x] Crash if settings are saved.
- [x] Help menu does not show the controls for android.
- [x] Hide the spilt play or add controls for player 2.
- [x] #111. All text and buttons are very small for high resolution devices with e.g. a 5" screen.
- [ ] #107. Fix unstable Travis builds.
- [x] #113. Crash sometimes at startup.
- [x] Path to home folder is wrong ("/"). (Fixed with a88314ad70facfcb5fce2418f5c6e0200990a950, todo is to use dedicated folder).

Feel free to add, remove and modify items on the list.

**Comment by TheJosh** [comment]
Closing this as all remaining items have their own issues
